CREATE TABLE `job_info` (
	`job_id` VARCHAR(50) NOT NULL COLLATE 'utf8mb3_general_ci',
	`job_name` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb3_general_ci',
	`job_desc` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb3_general_ci',
	`job_stats` VARCHAR(150) NULL DEFAULT NULL COLLATE 'utf8mb3_general_ci',
	`job_cron_expression` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb3_general_ci',
	`job_params` VARCHAR(2000) NULL DEFAULT NULL COLLATE 'utf8mb3_general_ci',
	`error_skip_yn` VARCHAR(1) NOT NULL DEFAULT 'N' COLLATE 'utf8mb3_general_ci',
	`use_yn` VARCHAR(1) NOT NULL DEFAULT 'Y' COLLATE 'utf8mb3_general_ci',
	`created_id` VARCHAR(20) NOT NULL COLLATE 'utf8mb3_general_ci',
	`created_time` DATETIME NOT NULL DEFAULT current_timestamp(),
	`modified_id` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb3_general_ci',
	`modified_time` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`job_id`) USING BTREE
)
COLLATE='utf8mb3_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `JOB_SUCCEED_HISTORY` (
	`JOB_EXECUTION_ID` BIGINT(20) NOT NULL,
	`JOB_ID` VARCHAR(50) NOT NULL,
	`JOB_NAME` VARCHAR(50) NULL DEFAULT NULL,
	`START_TIME` DATETIME(6) NULL DEFAULT NULL,
	`END_TIME` DATETIME(6) NULL DEFAULT NULL,
	`DIFF_SECONDS` INT(10),
	`COMMIT_COUNT` BIGINT(20) NULL DEFAULT NULL,
	`READ_COUNT` BIGINT(20) NULL DEFAULT NULL,
	`FILTER_COUNT` BIGINT(20) NULL DEFAULT NULL,
	`WRITE_COUNT` BIGINT(20) NULL DEFAULT NULL,
	`READ_SKIP_COUNT` BIGINT(20) NULL DEFAULT NULL,
	`WRITE_SKIP_COUNT` BIGINT(20) NULL DEFAULT NULL,
	`PROCESS_SKIP_COUNT` BIGINT(20) NULL DEFAULT NULL,
	`ROLLBACK_COUNT` BIGINT(20) NULL DEFAULT NULL,	
	`JOB_PARAMS` VARCHAR(2000) NULL DEFAULT NULL,
	PRIMARY KEY (`JOB_EXECUTION_ID`, `JOB_ID`) USING BTREE
)
COLLATE='utf8mb3_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `JOB_FAILED_HISTORY` (
	`JOB_EXECUTION_ID` BIGINT(20) NOT NULL,
	`JOB_ID` VARCHAR(50) NOT NULL,
	`JOB_NAME` VARCHAR(50) NULL DEFAULT NULL,
	`JOB_STATUS` VARCHAR(10) NULL DEFAULT NULL,
	`START_TIME` DATETIME(6) NULL DEFAULT NULL,
	`END_TIME` DATETIME(6) NULL DEFAULT NULL,
	`DIFF_SECONDS` INT(10),
	`COMMIT_COUNT` BIGINT(20) NULL DEFAULT NULL,
	`READ_COUNT` BIGINT(20) NULL DEFAULT NULL,
	`FILTER_COUNT` BIGINT(20) NULL DEFAULT NULL,
	`WRITE_COUNT` BIGINT(20) NULL DEFAULT NULL,
	`READ_SKIP_COUNT` BIGINT(20) NULL DEFAULT NULL,
	`WRITE_SKIP_COUNT` BIGINT(20) NULL DEFAULT NULL,
	`PROCESS_SKIP_COUNT` BIGINT(20) NULL DEFAULT NULL,
	`ROLLBACK_COUNT` BIGINT(20) NULL DEFAULT NULL,	
	`JOB_PARAMS` VARCHAR(2000) NULL DEFAULT NULL,
	`ERROR_TYPE` VARCHAR(200) NULL DEFAULT NULL,
	`ERROR_MESSAGE` TEXT NULL DEFAULT NULL,
	PRIMARY KEY (`JOB_EXECUTION_ID`, `JOB_ID`) USING BTREE
)
COLLATE='utf8mb3_general_ci'
ENGINE=InnoDB
;