export const ARR_GRID_LAYOUTS = [
    {
        title: '테스트1',
        x: 0,
        y: 0,
        w: 3,
        h: 2,
        auto_position: true,
        widget: 'TestGrid',
    },
    {
        title: '테스트2',
        x: 3,
        y: 0,
        w: 3,
        h: 2,
        auto_position: true,
        widget: 'TestGrid',
    },
    {
        title: '테스트3',
        x: 6,
        y: 0,
        w: 3,
        h: 2,
        auto_position: true,
        widget: 'TestGrid',
    },
    {
        title: '테스트4',
        x: 9,
        y: 0,
        w: 3,
        h: 2,
        auto_position: true,
        widget: 'TestGrid',
    },
    {
        title: '테스트5',
        x: 0,
        y: 2,
        w: 6,
        h: 2,
        auto_position: true,
        widget: 'TestGrid',
    },
    {
        title: '테스트6',
        x: 6,
        y: 2,
        w: 6,
        h: 2,
        auto_position: true,
        widget: 'TestGrid',
    },
    {
        title: '테스트7',
        x: 0,
        y: 4,
        w: 12,
        h: 3,
        auto_position: true,
        widget: 'TestGrid',
    },
];