spring:
  profiles:
    active: local

server:
  port: 8080

security:
  jjwt:
    secret: pdfaf!rser@dfasdf#$%^pdfaf!rser@dfasdf#$%^
    expiration: 3000000\
  password:
    encoder:
      secret: fasdfasfsdaf!@
      iteration: 3000
      keylength: 12