spring:
  profiles:
    active: local
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE    
    
dbconn:
  mariadb:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://127.0.0.1:3306/test
        username: test
        password: test   
        hikari:
          auto-commit: false
          pool-name: pkj  
          minimum-idle: 10
          maximum-pool-size: 20 
#  secondary:
#    datasource:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3308/SCHEMA_NAME?serverTimezone=UTC&characterEncoding=UTF-8
#      username: root
#      password: password    

server:
  port: 8080

security:
  jjwt:
    secret: pdfaf!rser@dfasdf#$%^pdfaf!rser@dfasdf#$%^
    expiration: 1000000
  password:
    encoder:
      secret: fasdfasfsdaf!@
      iteration: 3000
      keylength: 12
      
batch:
  chunkSize: 10
  partitionerSize: 10